---

  - include: sbt_0.13.1.yml

  - name: API | Create app dir
    file: dest={{appconf[item]['install_dir']}} owner={{ansible_ssh_user}} group=admin mode=755 state=directory
    sudo: yes
    tags: api
    with_items: applist

  - name: API | Checkout app 
    git: repo={{appconf[item]['repo']}} dest={{appconf[item]['install_dir']}} version=master
    register: checkout
    tags: api
    with_items: applist

  - name: API | Change ownership of checkout directory
    sudo: yes
    action: shell chown -R {{ansible_ssh_user}}:admin {{appconf[item]['install_dir']}}
    with_items: applist

  - name: API | Copy upstart script for app
    action: template src={{item}}.conf.j2 dest=/etc/init/{{item}}.conf
    register: upstart
    sudo: yes
    tags: api
    with_items: applist

  - name:  API | Generate start script for app
    action: command chdir={{appconf[item]['install_dir']}} sbt stage
    when: checkout.changed
    sudo: yes
    tags: api
    with_items: applist

  - name: API | Ensure apps are running
    command: echo "{{item}} is active? {{appconf[item]['active']}}"
    when: appconf[item]['active'] == True
    notify: API | Restart {{item}}
    with_items: applist
    tags: api

  - include: database.yml
