---
  - name: Linkbaiter | Create app dir
    file: dest={{linkbaiter_install_dir}} owner={{ansible_ssh_user}} group=admin mode=755 state=directory
    sudo: yes
    tags: linkbaiter

  - name: Linkbaiter | Checkout app 
    git: repo={{linkbaiter_repo}} dest={{linkbaiter_install_dir}} version=master
    register: checkout
    tags: linkbaiter

  - name: Linkbaiter | Change ownership of checkout directory
    sudo: yes
    action: shell chown -R {{ansible_ssh_user}}:admin {{linkbaiter_install_dir}}
    tags: linkbaiter

  - name: Linkbaiter | python dependencies
    sudo: yes
    pip: name={{item.key}} state=present version={{item.version}} use_mirrors=no
    with_items:
      - { key: MySQL-python, version: 1.2.5 }
      - { key: scrapy, version: 0.22.2 }
    tags: linkbaiter

  - name: Linkbaiter | create database
    mysql_db: name={{ linkbaiter_db_name }} state=present
    tags: linkbaiter

  - name: Linkbaiter | Import database schema
    sudo: yes
    mysql_db: name={{ linkbaiter_db_name }} state=import login_host=127.0.0.1 target={{linkbaiter_install_dir}}/schema.sql 
    tags: linkbaiter

  - name: Linkbaiter | Create crontab entry
    sudo: yes
    template: src=linkbaiter.sh.j2 dest=/etc/cron.hourly/linkbaiter owner=root group=root mode=0755
    tags: linkbaiter


