---
- name: Nginx | Install
  action: apt pkg=$item update-cache=yes force=yes state=present
  with_items:
    - nginx-extras
    - lua-zlib
    - lua-cjson
    - lua-nginx-memcached
    - lua5.1
    - liblua5.1-0
    - liblua5.1-0-dev
  sudo: yes
  tags: nginx

