---
- name: Nginx | Copy static content
  git: repo=https://github.com/opyate/uys.io dest={{stuff}}/uys.io/static version=master
  sudo: yes
  notify: Client | Restart nginx
  tags: static

# wedding.uys.io

- name: Nginx | ensure wedding site exists
  file: dest=/opt/wedding.uys.io state=directory
  sudo: yes

- name: Nginx | Copy static content for wedding
  git: repo=https://github.com/opyate/wedding-website dest=/opt/wedding.uys.io version=master
  sudo: yes
  notify: Client | Restart nginx
  tags: static

