---
- name: Common setup | Install common apt packages
  action: apt pkg=$item update-cache=yes state=present
  with_items:
    - python-software-properties
    - python-pip
    - python-dev
    - python-mysqldb
    - libxml2-dev
    - libxslt1-dev
    - libmysqlclient-dev
    - libssl-dev
    - reptyr
    # TODO MOTD for the next 3
    - htop
    - iotop
    - glances
    - curl
    - build-essential
    - git
    - unzip
    - iptables-persistent
    - redis-server
    - mysql-server
  sudo: yes
  tags: common

- name: Common setup | upgrade servers
  sudo: yes 
  apt: upgrade=full
